{
  "name": "hairbot",
  "version": "1.0.0",
  "description": "Telegram бот для анализа формы лица и подбора стрижек с использованием OpenAI",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "start": "node index.js",
    "dev": "nodemon src/index.js",
    "test": "jest --passWithNoTests",
    "lint": "eslint .",
    "format": "prettier --write .",
    "format:check": "prettier --check .",
    "setup": "npm install && npm run db:create && npm run db:seed",
    "db:create": "node scripts/create-tables.js",
    "db:seed": "node scripts/seed-database.js",
    "db:backup": "node scripts/backup-db.js",
    "db:backup:list": "node scripts/backup-db.js --list",
    "db:migrate": "node scripts/migrate-db.js",
    "db:cleanup": "node scripts/cleanup-db.js",
    "db:stats": "node scripts/show-stats.js --database",
    "webhook:setup": "node scripts/setup-webhook.js",
    "webhook:info": "node scripts/setup-webhook.js info",
    "webhook:delete": "node scripts/setup-webhook.js delete",
    "health": "node scripts/check-health.js",
    "clean": "rm -rf node_modules logs backups",
    "clean:logs": "rm -f logs/*.log && echo '✅ Логи очищены'",
    "clean:backups": "rm -f backups/*.sql backups/*.db && echo '✅ Бэкапы очищены'",
    "clean:modules": "rm -rf node_modules && echo '✅ Node modules удалены'",
    "deploy": "npm run lint && npm test && npm run check-env:ci && npm start",
    "docker:build": "docker build -t hairbot .",
    "docker:run": "docker run -p 3000:3000 --env-file .env hairbot",
    "docker:run:dev": "docker run -p 3000:3000 -v $(pwd):/app --env-file .env hairbot",
    "docker:compose": "docker-compose up",
    "docker:compose:build": "docker-compose up --build",
    "docker:compose:down": "docker-compose down",
    "docker:compose:logs": "docker-compose logs -f",
    "check-env": "node scripts/check-env.js",
    "check-env:ci": "node scripts/check-env-ci.js",
    "check-env:create": "node scripts/check-env.js --create",
    "check-env:strict": "node scripts/check-env.js --strict",
    "logs": "npm run logs:view",
    "logs:view": "tail -f logs/*.log 2>/dev/null || echo '⚠️  Файлы логов не найдены'",
    "logs:error": "tail -f logs/error.log 2>/dev/null || echo '⚠️  Файл error.log не найден'",
    "logs:app": "tail -f logs/app.log 2>/dev/null || echo '⚠️  Файл app.log не найден'",
    "logs:clear": "npm run clean:logs",
    "stats": "node scripts/show-stats.js",
    "stats:detailed": "node scripts/show-stats.js --detailed",
    "stats:system": "node scripts/show-stats.js --system",
    "stats:memory": "node scripts/show-stats.js --memory",
    "check:all": "npm run check-env && npm run check-health && npm run stats",
    "check:quick": "npm run check-env && echo '✅ Базовая проверка пройдена'",
    "check:ci": "npm run lint && npm test && npm run check-env:ci",
    "backup:all": "npm run db:backup && cp .env backups/.env.backup && echo '✅ Полный бэкап создан'",
    "audit": "npm audit",
    "audit:fix": "npm audit fix",
    "dev:watch": "nodemon --watch src --ext js,json --exec npm run dev",
    "dev:debug": "NODE_ENV=development nodemon --inspect src/index.js",
    "dev:with-db": "npm run db:create && npm run db:seed && npm run dev",
    "prod:setup": "npm ci --only=production && npm run check-env:ci",
    "prod:start": "NODE_ENV=production node index.js",
    "prod:with-backup": "npm run db:backup && npm run prod:start",
    "reset": "npm run clean && npm install && npm run setup",
    "reset:hard": "npm run clean && rm -f package-lock.json && npm install && npm run setup",
    "update": "npm update",
    "update:all": "npx npm-check-updates -u && npm install",
    "postinstall": "npm run check-env:ci || echo 'Проверка окружения пропущена'",
    "prestart": "",
    "predeploy": "npm run check:ci"
  },
  // ... остальная часть package.json без изменений
}
